### PR TITLE
Fix bug where oneOf would not retry other paths because offset would change

### PR DESCRIPTION
**Pull request by BobertForever**
Previously, in some oneOf cases, like `parser::statementParser`, we would never try other branches because the offset would change, and we'd consider that an error. In order to alleviate this, I've wrapped the parser in an `attempt` which will reset the offset before trying the next branch, which allows for other branches to potentially succeed where they wouldn't before

### CODE REVIEW

**Comment by akheron** [comment]
I don't think this is the correct fix. You should add `attempt` manually to the call site instead:

Before:
```
oneOf(a, b, c)
```

After:
```
oneOf(attempt(a), b, c)
```

The idea behind this is that `attempt` slows down parsing, so you should only use it when necessary, i.e. when `a` above may consume some input but still fail to match as a whole.

**Comment by BobertForever** [comment]
The thing that triggered me to dig into this was the following line:

https://github.com/akheron/sqltyper/blob/main/src/parser/index.ts#L835

I'm happy to wrap all 4 (well... the first 3) of the main statement types in an `attempt` clause and see if that works, but what I found was that the parser didn't attempt any of the other branches because the `select` parser had updated the offset.

**Comment by BobertForever** [comment]
It's also entirely possible that there's another issue somewhere lower that I've covered up with the `attempt` calls, but I was not able to find it trivially. Naively, it does make sense to me that we want to try all of the various branches in a `oneOf` statement even if they do move the offset since it may not be guaranteed that none of the branches don't update it. But, that is only my naive understanding :)

**Comment by akheron** [comment]
Hmm, I see. At least all of `select`, `insert` and `update` can start with `WITH`, so actually we now only support `SELECT` starting with a `WITH`. If you have `WITH ... UPDATE`, it will never match because of this attempt problem.

So yes, you could use `attempt` there, or alternatively refactor `statementParser` to be something like
```
oneOf(
  seq(optional(withQueries), oneOf(select, insert, update)),
  delete_
)
```
with the appropriate changes to `select`, `insert`, `update` and their respective AST constructors.

**Comment by BobertForever** [comment]
I implemented your suggestion, but have not yet tested it on my codebase. I'm unsure of my approach, where I've changed it so that the CTEs are passed in separately as a tuple and destructured in AST.walk. There was some code that was re-using the AST walking for subqueries which I had to add a hacky workaround for since that subquery can never technically use CTEs. Additionally it made the types surrounding AST/ Statement far more complex. Please let me know what you think or if there's a better way to implement this. Another approach could be having the parser add the CTEs into the statement types in the `seq` call, but I didn't do that because //technically// it's only possible to have CTEs at the top-level.

**Comment by akheron** [comment]
I just tested, and it seems that CTEs are supported also in subqueries in Postgres. This works for example:

```
select * from (
  with foo as (
    select 1 as a, 2 as b, 3 as c
  )
  select c, b, a
  from foo
) bar
```

So maybe it’s best to just add the `attempt` calls to `statementParser`. In any case, that’s better than adding them inside `oneOf` that’s used all over the parser.

**Comment by akheron** [comment]
See #322 for my take on a fix

**Comment by akheron** [comment]
Fixed in #322

**Comment by akheron** [comment]
Now that #322 is merged, I realized that it's not a good fix to sprinkle `attempts` there after all. It makes error messages very bad, because if there's illegal syntax in `SELECT`, the `INSERT` is tried next and the error message is thrown away. In the end, the only error message the user gets is that none of `SELECT`, `INSERT`, `UPDATE` or `DELETE` could be parsed correctly.

**Pull request closed without merging**
